default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: dl64
  password: define
  host: localhost

development:
  <<: *default
  database: api_testing_development

test:
  <<: *default
  database: api_testing_test

production:
  <<: *default
  database: api_testing_production
